### ISSUE TITLE
support Zoom's web client

### ISSUE THREAD

**Issue by mvdan** [joeywatts/gmeet-disable-autogain-control-extension#1]
Thanks so much for this extension! I mainly use Firefox, but I jump to Chromium sometimes since it supports screensharing on Wayland and sometimes plays more nicely with Google services.

Since your javascript code to disable auto-gain seems generic enough, perhaps we could support other webrtc video calling apps like Zoom's web client. I realise that they have a native desktop app, but many people choose to avoid the desktop app for various reasons (like, coincidentally, no Wayland screensharing support).

**Comment by mvdan** [comment]
Or rather, this could be reworded to supporting any webrtc web app. I assume the problem there is that you don't want to give the extension permission to every domain/site under the sun.

Perhaps we could keep a list of well-known webrtc web apps instead.

**Comment by RomanOnARiver** [comment]
Correct me if I'm wrong, but the only thing locking it to the websites it currently runs on is the manifest.json file - I feel like it's something you could easily do if you have any text editor, but I like the idea.

**Comment by mvdan** [comment]
Indeed, this would be a simple update to the file. It's much easier to install the readily-available plugin from the store directly, though :)

**Comment by joeywatts** [comment]
I've submitted an update for review in the Chrome Web Store that allows the extension to be applied to any domain.

**Comment by mvdan** [comment]
Thank you!
