### ISSUE TITLE
Not working on MS Teams

### ISSUE THREAD

**Issue by RaulCorreia** [joeywatts/gmeet-disable-autogain-control-extension#4]
I tested it at google meet and it worked perfectly but in meetings at microsoft teams (Web Version) it didn't work, keeps changing the microphone volume.

Chrome V: 87.0.4280.88

**Comment by joeywatts** [comment]
Submitted a new release for review in the Chrome WebStore, so an update (v1.2) with support for MS Teams should be coming soon!
